name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: pipenv install --dev
    - name: black
      run: pipenv run black . --check --exclude "/migrations/.*\.py$"
    - name: flake8
      run: pipenv run flake8
    - name: missing migrations
      run: pipenv run ./manage.py makemigrations --check --dry-run
    - name: run migrations
      run: pipenv run ./manage.py migrate
